name: Bump a package

on:
  workflow_dispatch:
    inputs:
      package:
        description: "A package to be bumped"
        type: choice
        required: true
        options:
          - nestjs-denokv
          - nestjs-platform-oak
      new-version:
        description: "A new version to be published"
        type: string
        required: true
      current-version:
        description: "The current (latest) version of the specified package"
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Get deno version
        id: deno-version
        run: |
          echo "version=$(cat .deno-version)" >> ${GITHUB_OUTPUT}
      - name: Set up Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: ${{ steps.deno-version.outputs.version }}
      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v2.0.1
        with:
          version: 2.5.0
      - name: Update CHANGELOG.md and deno.json of the package
        run: |
          deno run --allow-read=. --allow-write=. --allow-run=git-cliff,deno \
            tools/bump-package.ts \
            --package ${{ inputs.package }} \
            --current-version ${{ inputs.current-version }} \
            --new-version ${{ inputs.new-version }}
      - name: Commit changes
        run: |
          git checkout -b '${{ inputs.package }}@${{ inputs.new-version }}'
          git add --all
          git commit -m 'chore: release `${{ inputs.package }}@${{ inputs.new-version }}`'
      - name: Create a PR
        run: |
          gh pr create \
            --base main \
            --title 'chore: release `${{ inputs.package }}@${{ inputs.new-version }}`'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
